# Generated by Django 4.1.2 on 2022-10-20 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('rank', models.FloatField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'In Approved'), (3, 'Active'), (4, 'Frozen'), (5, 'Deleted')], default=3)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.comment')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('latitude', models.CharField(blank=True, max_length=12, null=True)),
                ('longitude', models.CharField(blank=True, max_length=12, null=True)),
                ('phone_number', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=220)),
                ('service_phone_number', models.CharField(max_length=30)),
                ('logo', models.FileField(blank=True, null=True, upload_to='service_logos')),
                ('rank', models.FloatField(default=0.0)),
                ('type', models.IntegerField(choices=[(1, 'Default'), (2, 'Silver'), (3, 'Gold'), (4, 'Premium'), (5, 'Diamond')], default=1)),
                ('is_premium', models.BooleanField(default=False)),
                ('sort_number', models.IntegerField(default=0)),
                ('view_count', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'In Approved'), (3, 'Active'), (4, 'Frozen'), (5, 'Deleted')], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.country')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.district')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to=settings.AUTH_USER_MODEL)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.region')),
            ],
            options={
                'verbose_name_plural': 'Service',
                'db_table': 'service',
            },
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=220)),
                ('description', models.TextField()),
                ('sort_number', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'In Approved'), (3, 'Active'), (4, 'Frozen'), (5, 'Deleted')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='WorkingDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday'), (6, 'Saturday'), (7, 'Sunday')])),
                ('work_start', models.DateTimeField()),
                ('work_end', models.DateTimeField()),
                ('launch_start', models.DateTimeField()),
                ('launch_end', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ServiceImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to='service_image')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'In Approved'), (3, 'Active'), (4, 'Frozen'), (5, 'Deleted')], default=1)),
                ('sort_number', models.IntegerField(default=0)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.service')),
            ],
        ),
        migrations.CreateModel(
            name='CommentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='')),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'In Approved'), (3, 'Active'), (4, 'Frozen'), (5, 'Deleted')], default=1)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.service'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('sort_number', models.IntegerField(default=0)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'In Approved'), (3, 'Active'), (4, 'Frozen'), (5, 'Deleted')], default=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='service.category')),
            ],
        ),
    ]
